name: travenx
description: Travenx - eyes' desire
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # load images from internet
  cached_network_image: ^3.2.0

  # get vector file as image
  flutter_svg: ^1.0.3

  # get readmore button package
  readmore: ^2.1.0

  # state management package
  provider: ^6.0.2

  # Firebase Authentication
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.10

  # Flutter Facebook Authentication
  flutter_facebook_auth: ^4.1.1

  # Flutter Google Sign In
  google_sign_in: ^5.2.4

  # Loading Screen
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.1

  # Firebase Cloud Firestore
  cloud_firestore: ^3.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
